[[FileUnv]]
arch = "x86_64"
git-tree-sha1 = "e31a8de5c57a90955f06bc7e3e62928141109204"
libc = "glibc"
os = "linux"

    [[FileUnv.download]]
    sha256 = "e2e632196f2c8def4373199febffb7fe4846f0d8f986a26d4ad924df5f00fdfa"
    url = "https://github.com/a-mikhaylov/FileUnv_jll.jl/releases/download/FileUnv-v1.0.10+0/FileUnv.v1.0.10.x86_64-linux-gnu.tar.gz"
[[FileUnv]]
arch = "x86_64"
git-tree-sha1 = "56ad526ae25024befb5c18735fb2891a8f3db8df"
os = "windows"

    [[FileUnv.download]]
    sha256 = "171063b2c0155b4c2cebd91e1eebf406ddbebd50e11f4b01b0e9a1c890230778"
    url = "https://github.com/a-mikhaylov/FileUnv_jll.jl/releases/download/FileUnv-v1.0.10+0/FileUnv.v1.0.10.x86_64-w64-mingw32.tar.gz"
