[[FileUnv]]
arch = "x86_64"
git-tree-sha1 = "c7827c6399f424e4949a7fa6804d62ce7b59fb25"
libc = "glibc"
os = "linux"

    [[FileUnv.download]]
    sha256 = "ce2c1e0b275a5dde87bce6a1d840e5ffd258aa9770ecab908165223035c094ae"
    url = "https://github.com/a-mikhaylov/FileUnv_jll.jl/releases/download/FileUnv-v1.0.6+0/FileUnv.v1.0.6.x86_64-linux-gnu.tar.gz"
[[FileUnv]]
arch = "x86_64"
git-tree-sha1 = "95aae100699fea96a85f9e80d401b0611118edd4"
os = "windows"

    [[FileUnv.download]]
    sha256 = "2d554bc49edf7d50c3b82d6184d378ee1e782576f46a6f2c51f5a90be5c09a44"
    url = "https://github.com/a-mikhaylov/FileUnv_jll.jl/releases/download/FileUnv-v1.0.6+0/FileUnv.v1.0.6.x86_64-w64-mingw32.tar.gz"
