# Autogenerated wrapper script for FileUnv_jll for x86_64-w64-mingw32
export FileUnv

JLLWrappers.@generate_wrapper_header("FileUnv")
JLLWrappers.@declare_library_product(FileUnv, "libFileUnv.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        FileUnv,
        "bin\\libFileUnv.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
