# Autogenerated wrapper script for FileUnv_jll for x86_64-linux-gnu
export FileUnv

JLLWrappers.@generate_wrapper_header("FileUnv")
JLLWrappers.@declare_library_product(FileUnv, "libFileUnv.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        FileUnv,
        "lib/libFileUnv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
